title = "StableDiscord Configuration"

[auth]
discord_token="XXX"

[discord.settings]
# Set channels that the bot listens and responds on. Specify in case-sensitive "server:channel" format
# If both are set, only listen_channels is used. If neither are set, the bot will listen on all channels it is invited.
listen_channels = []
ignore_channels = []

# Set users that the bot listens and responds to. Specify in case-sensitive "username#id" format
# If both are set, only listen_users is used. If neither are set, the bot will listen to all members, but never itself.
listen_users = []
ignore_users = []

wake_word = "/art"

[discord.style]
ack_emoji: str = "ğŸ‘"
in_prog_emoji: str = "â±ï¸"
done_emoji: str = "ğŸ’¯"

[diffuser.settings]
use_gpu = true
use_half_precision = true
enable_xformers_attention = true

[misc_settings]
log_dir="logs"
